GET http://localhost:3003/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxhcyIsImlkIjoiNjc1YWNmZTBiZGE5Y2RiMDA1YjgwY2E1IiwiaWF0IjoxNzM0NjcyNDQxLCJleHAiOjE3MzQ2NzYwNDF9.Wa3Sw0z8PFZoGUUZirvHBLeDcBGKR8xAHubV8DT81hg

